version: '3.1'
services:
    mysql:
        image: mysql:5.7.22
        container_name: catssyssql
        environment:
            - MYSQL_DATABASE=catssys
            - MYSQL_USER=catssysdev
            - MYSQL_PASSWORD=catssysdev
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - .:/srv/vhosts/phpApp
            - ./.docker/mysql/mysql-data:/var/lib/mysql
        working_dir: /srv/vhosts/phpApp
        ports:
            - 13306:3306

    node:
        image: node:10.6.0-alpine
        container_name: catssysjs
        environment:
            - SERVERNAME=php
        volumes:
            - .:/srv/vhosts/phpApp
        working_dir: /srv/vhosts/phpApp
        command: /bin/sh -c "npm install && npm run dev"
        ports:
            - 3000:3000
            - 3001:3001
        depends_on:
            - php

    php:
        # image: marciodojr/phpstart-apache-docker-image:dev # subir essa imagem para o dockerhub algum dia possivelmente com outro nome
        image: phpstart-apache:latest
        container_name: catssysphp
        environment:
            - APP_ENV=development
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_NAME=catssys
            - DB_USER=catssysdev
            - DB_PASS=catssysdev
        working_dir: /srv/vhosts/phpApp
        volumes:
            - .:/srv/vhosts/phpApp
            - ./.docker/php/php-ini-overrides.ini:/etc/php/7.2/apache2/conf.d/99-overrides.ini
            - ./.docker/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
            - ./logs/apache:/var/log/apache2
        ports:
            - 2999:80
        depends_on:
            - mysql