version: '3.1'
services:
    mysql:
        image: mysql:5.7.22
        container_name: catssys-mysql
        environment:
            - MYSQL_DATABASE=catssys
            - MYSQL_USER=catssysdev
            - MYSQL_PASSWORD=catssysdev
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - .:/srv/vhosts/phpApp
            - ./.docker/mysql/mysql-data:/var/lib/mysql
        working_dir: /srv/vhosts/phpApp
        ports:
            - 13306:3306

    node:
        image: node:10.6.0-alpine
        container_name: catssys-node
        environment:
            - SERVERNAME=webserver
        volumes:
            - .:/srv/vhosts/phpApp
        working_dir: /srv/vhosts/phpApp
        command: /bin/sh -c "npm install grunt-cli && npm install && npm run dev"
        ports:
            - 3000:3000
            - 3001:3001
        depends_on:
            - webserver

    php-fpm:
        # image: marciodojr/phpstart:2.1.0
        image: phpstart
        container_name: catssys
        environment:
            - APP_ENV=development
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_NAME=catssys
            - DB_USER=catssysdev
            - DB_PASS=catssysdev
        working_dir: /srv/vhosts/phpApp
        volumes:
            - .:/srv/vhosts/phpApp
            - ./.docker/php/php-ini-overrides.ini:/usr/local/etc/php/7.2/fpm/conf.d/99-overrides.ini
        command: /bin/sh -c "composer update && php-fpm"
        depends_on:
            - mysql

    webserver:
        image: nginx:1.14.0-alpine
        container_name: catssys-webserver
        working_dir: /srv/vhosts/phpApp
        volumes:
            - .:/srv/vhosts/phpApp
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 2999:80
        depends_on:
            - php-fpm